config/routes.rb
OnTheSpotTester::Application.routes.draw do

  get "home/about", :as => :about

  resources :posts do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end

  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TagHelper

  validate :check_test_capitalized



  def check_test_capitalized
    unless test_capitalized.nil?
      self.errors[:base] << "First letter must be a capital" unless self.test_capitalized == self.test_capitalized.capitalize
    end
  end

  def formatted_text
    simple_format(self.large_text).html_safe
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  can_edit_on_the_spot

  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def large_text
    klass,field,id = params[:id].split('__')
    @post = Post.find(id)

    render :text => @post.large_text
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def app_version
    "v#{APP_VERSION}".html_safe
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.haml
%section#about
  .page-header
    %h1
      About
      %small some information
  %p
    This is a small demo-project, showcasing the possibilities of
    = link_to 'on_the_spot', 'https://github.com/nathanvda/on_the_spot'
  %p
    Have a look at the
    = link_to 'source', 'https://github.com/nathanvda/on_the_spot_tester'
    of this project for more information.

app/views/layouts/application.html.haml
!!! Strict
%html{ "xml:lang" => "en", :lang => "en", :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %title== OnTheSpot Tester #{@page_title}
    %meta{'http-equiv' => "Content-Type", :content => "text/html; charset=utf-8"}

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'

    = csrf_meta_tag

  %body{:style => 'padding-top: 40px;'}
    .topbar
      .topbar-inner
        .container
          %h3
            = link_to "On the spot Tester", root_url
          %ul.nav
            %li
              =link_to "Home", root_url
            %li
              =link_to "About", about_path
    .container
      = yield
      %footer.footer
        .container
          %p
            On_the_spot is a
            = link_to '@dixis', 'http://twitter.com/dixis'
            realisation.
            %br
            = "&copy; 2011".html_safe
            |
            = app_version

app/views/posts/_form.html.haml
= form_for @post do |f|
  -if @post.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :story
    = f.text_field :story
  .field
    = f.label :rating
    = f.text_field :rating
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Author
    %th Title
    %th Story
    %th Rating
    %th Test capitalized
    %th

  - @posts.each do |post|
    %tr
      %td= on_the_spot_edit post, :author
      %td= post.title
      %td= on_the_spot_edit post, :story, :type => :textarea, :tooltip => 'Click to write story ...'
      %td= on_the_spot_edit post, :rating, :type => :select, :data => [[0, "Not rated"], [1, "Worse than bad"], [2, "Bad"], [3, "Mediocre"], [4, "Not bad"], [5, "Good"], [6, "Awesome"], [7, "Photoshopped!!"]]
      %td= on_the_spot_edit post, :test_capitalized
      %td
        = link_to 'Show', post
        |
        = link_to 'Edit', edit_post_path(post)
        |
        = link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New post', new_post_path



.alert-message.block-message.info{:style => 'margin-top: 20px;'}
  %p
    The editable fields will high-light on hover. Click the fields to edit them.
  %p
    Notice that you can edit all the values in the index-view. If an object would have nested objects, that
    would also be possible.
  %p
    On the show-page we also show some more specific examples ...

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%h2
  Show the post
  %small and edit some parts you really want to

%table.editable
  %tr
    %td
      %b Author:
    %td= on_the_spot_edit @post, :author
  %tr
    %td
      %b Title:
    %td= @post.title
  %tr
    %td
      %b Story:
    %td= @post.story
  %tr
    %td
      %b Rating:
    %td= @post.rating
  %tr
    %td
      %b Enabled:
    %td= on_the_spot_edit @post, :enabled, :type => :checkbox
  %tr
    %td
      %b Large (formatted) text:
    %td= on_the_spot_edit @post, :large_text, :type => :textarea, :display_method => :formatted_text



= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path